name: Deploy Azure Function (Backend)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Gatilho apenas se houver mudanças na pasta backend

env:
  AZURE_FUNCTION_APP_NAME: func-galeria # Seu Function App Name
  AZURE_FUNCTION_PACKAGE_PATH: 'backend' 
  PYTHON_VERSION: '3.12' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Instalação do driver ODBC (necessário para pyodbc rodar no Linux/Ubuntu)
      - name: Install ODBC Driver Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev

      # 2. Configura o ambiente Python
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      # 3. Resolve dependências do Python (pyodbc)
      - name: 'Resolve project dependencies'
        shell: bash
        run: |
          pip install --upgrade pip
          pip install -r ${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/requirements.txt

      # 4. Login e Deploy
      - name: 'Azure Login & Deploy'
        uses: azure/functions-action@v1
        id: deploy
        with:
          app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
          package: ${{ env.AZURE_FUNCTION_PACKAGE_PATH }}
          # Usa o Secret ORIGINAL criado a partir do XML da Azure Function.
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}